export default function PostmortemsPage() {
  return (
    <>
      <section className="hero">
        <div className="eyebrow">Review loop</div>
        <h1>Postmortems</h1>
        <p>
          Future postmortems will compare recommendations with actual gameweek
          outcomes and record lessons for the next decision cycle.
        </p>
      </section>

      <section className="grid">
        <article className="card">
          <h2>Milestone 1 status</h2>
          <p>No postmortems have been generated by the skeleton repo.</p>
        </article>
      </section>
    </>
  );
}
