export default function RecommendationsPage() {
  return (
    <>
      <section className="hero">
        <div className="eyebrow">Archive</div>
        <h1>Recommendations</h1>
        <p>
          Generated recommendation files will appear here after later milestones
          implement the recommendation command.
        </p>
      </section>

      <section className="grid">
        <article className="card">
          <h2>Milestone 1 status</h2>
          <p>No recommendations have been generated by the skeleton repo.</p>
        </article>
      </section>
    </>
  );
}
